// Copyright 2026 the V8 project authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is automatically generated by gen-keywords-gen-h.py and
// should not be modified manually.

#ifndef V8_PARSING_KEYWORDS_SPA_GEN_H_
#define V8_PARSING_KEYWORDS_SPA_GEN_H_

#include <cstring>

#include "src/parsing/token.h"

namespace v8 {
namespace internal {

class JsSpaKeywordHash {
 public:
  static inline Token::Value GetToken(const char* str, int len) {
    switch (len) {
      case 2:
        return std::strncmp(str, "si", len) == 0 ? Token::IF
            : std::strncmp(str, "en", len) == 0 ? Token::IN
                                                        : Token::IDENTIFIER;
      case 3:
        return std::strncmp(str, "sal", len) == 0 ? Token::BREAK
            : std::strncmp(str, "haz", len) == 0 ? Token::DO
            : std::strncmp(str, "por", len) == 0 ? Token::FOR
            : std::strncmp(str, "lee", len) == 0 ? Token::GET
            : std::strncmp(str, "sea", len) == 0 ? Token::LET
            : std::strncmp(str, "pon", len) == 0 ? Token::SET
            : std::strncmp(str, "var", len) == 0 ? Token::VAR
            : std::strncmp(str, "con", len) == 0 ? Token::WITH
                                                        : Token::IDENTIFIER;
      case 4:
        return std::strncmp(str, "caso", len) == 0 ? Token::CASE
            : std::strncmp(str, "sino", len) == 0 ? Token::ELSE
            : std::strncmp(str, "enum", len) == 0 ? Token::ENUM
            : std::strncmp(str, "nulo", len) == 0 ? Token::NULL_LITERAL
            : std::strncmp(str, "este", len) == 0 ? Token::THIS
            : std::strncmp(str, "cede", len) == 0 ? Token::YIELD
                                                        : Token::IDENTIFIER;
      case 5:
        return std::strncmp(str, "asinc", len) == 0 ? Token::ASYNC
            : std::strncmp(str, "clase", len) == 0 ? Token::CLASS
            : std::strncmp(str, "const", len) == 0 ? Token::CONST
            : std::strncmp(str, "borra", len) == 0 ? Token::DELETE
            : std::strncmp(str, "falso", len) == 0 ? Token::FALSE_LITERAL
            : std::strncmp(str, "enfin", len) == 0 ? Token::FINALLY
            : std::strncmp(str, "nuevo", len) == 0 ? Token::NEW
            : std::strncmp(str, "super", len) == 0 ? Token::SUPER
            : std::strncmp(str, "lanza", len) == 0 ? Token::THROW
            : std::strncmp(str, "vacio", len) == 0 ? Token::VOID
                                                        : Token::IDENTIFIER;
      case 6:
        return std::strncmp(str, "espera", len) == 0 ? Token::AWAIT
            : std::strncmp(str, "atrapa", len) == 0 ? Token::CATCH
            : std::strncmp(str, "cambio", len) == 0 ? Token::SWITCH
            : std::strncmp(str, "cierto", len) == 0 ? Token::TRUE_LITERAL
            : std::strncmp(str, "prueba", len) == 0 ? Token::TRY
            : std::strncmp(str, "tipode", len) == 0 ? Token::TYPEOF
                                                        : Token::IDENTIFIER;
      case 7:
        return std::strncmp(str, "defecto", len) == 0 ? Token::DEFAULT
            : std::strncmp(str, "exporta", len) == 0 ? Token::EXPORT
            : std::strncmp(str, "funcion", len) == 0 ? Token::FUNCTION
            : std::strncmp(str, "importa", len) == 0 ? Token::IMPORT
            : std::strncmp(str, "paquete", len) == 0 ? Token::FUTURE_STRICT_RESERVED_WORD
            : std::strncmp(str, "privado", len) == 0 ? Token::FUTURE_STRICT_RESERVED_WORD
            : std::strncmp(str, "publico", len) == 0 ? Token::FUTURE_STRICT_RESERVED_WORD
                                                        : Token::IDENTIFIER;
      case 8:
        return std::strncmp(str, "continua", len) == 0 ? Token::CONTINUE
            : std::strncmp(str, "extiende", len) == 0 ? Token::EXTENDS
            : std::strncmp(str, "interfaz", len) == 0 ? Token::FUTURE_STRICT_RESERVED_WORD
            : std::strncmp(str, "devuelve", len) == 0 ? Token::RETURN
            : std::strncmp(str, "estatico", len) == 0 ? Token::STATIC
            : std::strncmp(str, "mientras", len) == 0 ? Token::WHILE
                                                        : Token::IDENTIFIER;
      case 9:
        return std::strncmp(str, "depurador", len) == 0 ? Token::DEBUGGER
            : std::strncmp(str, "protegido", len) == 0 ? Token::FUTURE_STRICT_RESERVED_WORD
                                                        : Token::IDENTIFIER;
      case 10:
        return std::strncmp(str, "implementa", len) == 0 ? Token::FUTURE_STRICT_RESERVED_WORD
                                                        : Token::IDENTIFIER;
      case 11:
        return std::strncmp(str, "instanciade", len) == 0 ? Token::INSTANCEOF
                                                        : Token::IDENTIFIER;
      default:
        return Token::IDENTIFIER;
    }
  }
};

}  // namespace internal
}  // namespace v8

#endif  // V8_PARSING_KEYWORDS_SPA_GEN_H_
