// Copyright 2026 the V8 project authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is automatically generated by gen-keywords-spa-gen-h.py and
// should not be modified manually.

#ifndef V8_PARSING_KEYWORDS_SPA_GEN_H_
#define V8_PARSING_KEYWORDS_SPA_GEN_H_

#include <cstring>

#include "src/parsing/token.h"

namespace v8 {
namespace internal {

class JsSpaKeywordHash {
 public:
  static inline Token::Value GetToken(const char* str, int len) {
    switch (len) {
      case 2:
        return std::strncmp(str, "si", len) == 0 ? Token::IF
                                                        : Token::IDENTIFIER;
      case 4:
        return std::strncmp(str, "sino", len) == 0 ? Token::ELSE
                                                        : Token::IDENTIFIER;
      case 7:
        return std::strncmp(str, "funcion", len) == 0 ? Token::FUNCTION
                                                        : Token::IDENTIFIER;
      case 8:
        return std::strncmp(str, "devuelve", len) == 0 ? Token::RETURN
                                                        : Token::IDENTIFIER;
      default:
        return Token::IDENTIFIER;
    }
  }
};

}  // namespace internal
}  // namespace v8

#endif  // V8_PARSING_KEYWORDS_SPA_GEN_H_
