// Copyright 2026 the V8 project authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is automatically generated by tools/gen-keywords/gen-pseudokeywords-gen-h.py and
// should not be modified manually.

#ifndef V8_PARSING_PSEUDOKEYWORDS_GEN_H_
#define V8_PARSING_PSEUDOKEYWORDS_GEN_H_

#include "src/ast/ast-value-factory.h"
#include "src/base/logging.h"
#include "src/parsing/source-dialect.h"

namespace v8 {
namespace internal {

enum class PseudoKeywordName : uint8_t {
  kArguments,
  kAs,
  kConstructor,
  kEval,
  kFrom,
  kMeta,
  kOf,
  kProto,
  kTarget,
};

class JsEngPseudoKeywordNameMap {
 public:
  static inline const char* GetSpelling(PseudoKeywordName name) {
    switch (name) {
      case PseudoKeywordName::kArguments:
        return "arguments";
      case PseudoKeywordName::kAs:
        return "as";
      case PseudoKeywordName::kConstructor:
        return "constructor";
      case PseudoKeywordName::kEval:
        return "eval";
      case PseudoKeywordName::kFrom:
        return "from";
      case PseudoKeywordName::kMeta:
        return "meta";
      case PseudoKeywordName::kOf:
        return "of";
      case PseudoKeywordName::kProto:
        return "__proto__";
      case PseudoKeywordName::kTarget:
        return "target";
    }
    UNREACHABLE();
  }
};

class JsSpaPseudoKeywordNameMap {
 public:
  static inline const char* GetSpelling(PseudoKeywordName name) {
    switch (name) {
      case PseudoKeywordName::kArguments:
        return "argumentos";
      case PseudoKeywordName::kAs:
        return "como";
      case PseudoKeywordName::kConstructor:
        return "constructor";
      case PseudoKeywordName::kEval:
        return "eval";
      case PseudoKeywordName::kFrom:
        return "desde";
      case PseudoKeywordName::kMeta:
        return "meta";
      case PseudoKeywordName::kOf:
        return "de";
      case PseudoKeywordName::kProto:
        return "__proto__";
      case PseudoKeywordName::kTarget:
        return "dest";
    }
    UNREACHABLE();
  }
};

V8_INLINE const char* SourceDialectNameSpelling(SourceDialect source_dialect,
                                                PseudoKeywordName name) {
  switch (source_dialect) {
    case SourceDialect::kJsEng:
      return JsEngPseudoKeywordNameMap::GetSpelling(name);
    case SourceDialect::kJsSpa:
      return JsSpaPseudoKeywordNameMap::GetSpelling(name);
  }
  UNREACHABLE();
}

V8_INLINE bool AstRawStringEqualsSourceDialectName(
    const AstRawString* identifier, SourceDialect source_dialect,
    PseudoKeywordName name) {
  if (identifier == nullptr) return false;
  return identifier->IsOneByteEqualTo(
      SourceDialectNameSpelling(source_dialect, name));
}

}  // namespace internal
}  // namespace v8

#endif  // V8_PARSING_PSEUDOKEYWORDS_GEN_H_
