#!/usr/bin/env python3
# Copyright 2026 the V8 project authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import subprocess
from pathlib import Path


def repo_root_from_script(script_file):
  return Path(script_file).resolve().parents[2]


def script_relpath(script_file, root_dir):
  return Path(script_file).resolve().relative_to(root_dir).as_posix()


def call_with_input(cmd, input_string=""):
  process = subprocess.Popen(cmd,
                             stdin=subprocess.PIPE,
                             stdout=subprocess.PIPE,
                             stderr=subprocess.PIPE)
  stdout, _ = process.communicate(input_string.encode("utf-8"))
  retcode = process.wait()
  if retcode != 0:
    raise subprocess.CalledProcessError(retcode, cmd)
  return stdout.decode("utf-8")


def read_entries(input_path):
  entries = []
  for raw_line in Path(input_path).read_text(encoding="utf-8").splitlines():
    line = raw_line.strip()
    if not line or line.startswith("#"):
      continue
    key, value = [part.strip() for part in line.split(",", 1)]
    entries.append((key, value))
  return entries


def clang_format(root_dir, text):
  clang_format_path = root_dir / "third_party/depot_tools/clang-format"
  try:
    return call_with_input([str(clang_format_path)], text)
  except subprocess.CalledProcessError:
    return text


def wrap_header(body, *, script_name, header_guard, includes):
  include_block = "\n".join(f'#include "{include}"' for include in includes)
  return f"""// Copyright 2026 the V8 project authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is automatically generated by {script_name} and
// should not be modified manually.

#ifndef {header_guard}
#define {header_guard}

{include_block}

namespace v8 {{
namespace internal {{

{body}

}}  // namespace internal
}}  // namespace v8

#endif  // {header_guard}
"""
