#!/usr/bin/env python3
# Copyright 2026 the V8 project authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import os
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
INPUT = ROOT / "src/parsing/keywords-spa.txt"
OUTPUT = ROOT / "src/parsing/keywords-spa-gen.h"


def read_entries():
  entries = []
  for raw_line in INPUT.read_text(encoding="utf-8").splitlines():
    line = raw_line.strip()
    if not line or line.startswith("#"):
      continue
    keyword, token = [part.strip() for part in line.split(",", 1)]
    entries.append((keyword, token))
  return entries


def emit(entries):
  lines = [
      "// Copyright 2026 the V8 project authors. All rights reserved.",
      "// Use of this source code is governed by a BSD-style license that can be",
      "// found in the LICENSE file.",
      "",
      "// This file is automatically generated by gen-keywords-spa-gen-h.py and",
      "// should not be modified manually.",
      "",
      "#ifndef V8_PARSING_KEYWORDS_SPA_GEN_H_",
      "#define V8_PARSING_KEYWORDS_SPA_GEN_H_",
      "",
      "#include <cstring>",
      "",
      "#include \"src/parsing/token.h\"",
      "",
      "namespace v8 {",
      "namespace internal {",
      "",
      "class JsSpaKeywordHash {",
      " public:",
      "  static inline Token::Value GetToken(const char* str, int len) {",
      "    switch (len) {",
  ]

  lengths = {}
  for keyword, token in entries:
    lengths.setdefault(len(keyword), []).append((keyword, token))

  for length in sorted(lengths):
    cases = lengths[length]
    lines.append(f"      case {length}:")
    for index, (keyword, token) in enumerate(cases):
      prefix = "        return " if index == 0 else "            : "
      comparator = f"std::strncmp(str, \"{keyword}\", len) == 0"
      lines.append(f"{prefix}{comparator} ? {token}")
    lines.append("                                                        : Token::IDENTIFIER;")

  lines.extend([
      "      default:",
      "        return Token::IDENTIFIER;",
      "    }",
      "  }",
      "};",
      "",
      "}  // namespace internal",
      "}  // namespace v8",
      "",
      "#endif  // V8_PARSING_KEYWORDS_SPA_GEN_H_",
      "",
  ])
  return "\n".join(lines)


def main():
  OUTPUT.write_text(emit(read_entries()), encoding="utf-8")


if __name__ == "__main__":
  main()
